# ==================== Server ====================
spring.application.name=product-service
server.port=8082

# ==================== Database ====================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5436/products_db}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin123}

# Hibernate validates that entities match the DB schema (Flyway manages the schema)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==================== Flyway ====================
spring.flyway.enabled=true

# ==================== Swagger ====================
springdoc.swagger-ui.path=/swagger-ui.html

# ==================== Actuator ====================
management.endpoints.web.exposure.include=health,info
