# ==================== CONFIG SERVER ====================
spring.config.import=optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8888

# ==================== Server ====================
spring.application.name=product-service
server.port=8082

# ==================== Database ====================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5436/products_db}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin123}

# Hibernate validates that entities match the DB schema (Flyway manages the schema)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==================== Flyway ====================
spring.flyway.enabled=true

# ==================== Swagger ====================
springdoc.swagger-ui.path=/swagger-ui.html

# ==================== Actuator ====================
management.endpoints.web.exposure.include=health,info,caches,prometheus

# ==================== Redis Cache ====================
# Redis connection — "localhost" for local dev, "redis" inside Docker.
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
# Cache type — tells Spring to use Redis as the cache backend (not in-memory)
spring.cache.type=redis

# ==================== EUREKA SERVICE DISCOVERY ====================
eureka.client.service-url.defaultZone=http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@${EUREKA_HOST:localhost}:8761/eureka
eureka.instance.prefer-ip-address=true

# ==================== DISTRIBUTED TRACING ====================
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [${spring.application.name}, %X{traceId:-}, %X{spanId:-}] %-5level %logger{36} - %msg%n
