package com.ecommerce.userservice.service;

import com.ecommerce.userservice.model.Role;
import com.ecommerce.userservice.model.User;
import com.ecommerce.userservice.model.UserStatus;
import com.ecommerce.userservice.repository.RoleRepository;
import com.ecommerce.userservice.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import java.util.List;
import java.util.Set;

// @Service — tells Spring "this class contains business logic".
// Spring creates ONE instance (a bean) and injects it wherever needed.
// This is the same as @Component, but communicates intent — this is a service.
@Service

// @RequiredArgsConstructor — Lombok generates a constructor with all "final" fields.
// This is how dependency injection works in Spring:
//   1. You declare a field as "final"
//   2. Lombok generates a constructor that takes those fields as parameters
//   3. Spring sees the constructor and automatically passes in the matching beans
//
// This replaces the old @Autowired approach and is the recommended way.
@RequiredArgsConstructor
public class UserService {

    // These are injected by Spring via the constructor (generated by @RequiredArgsConstructor).
    // "final" means they can't be reassigned after construction — a safety measure.
    private final UserRepository userRepository;
    private final RoleRepository roleRepository;

    // ==================== CREATE ====================

    // @Transactional — wraps this method in a database transaction.
    // If anything fails (exception thrown), ALL database changes in this method
    // are rolled back. The database stays consistent — no half-saved data.
    //
    // Without @Transactional: save user succeeds, but assigning role fails
    //   → you have a user with no role in the DB (broken state).
    // With @Transactional: if role assignment fails, the user save is also undone.
    @Transactional
    public User createUser(User user) {
        // Business rule: no duplicate emails
        if (userRepository.existsByEmail(user.getEmail())) {
            throw new IllegalArgumentException("Email already exists: " + user.getEmail());
        }

        // Set default status for new users
        user.setStatus(UserStatus.ACTIVE);

        // Assign the default ROLE_CUSTOMER to every new user
        Role customerRole = roleRepository.findByName("ROLE_CUSTOMER")
                .orElseThrow(() -> new RuntimeException("Default role ROLE_CUSTOMER not found"));
        user.setRoles(Set.of(customerRole));

        return userRepository.save(user);
    }

    // ==================== READ ====================

    // @Transactional(readOnly = true) — optimizes read operations.
    // Tells Hibernate "don't track changes to these entities" (no dirty checking).
    // This is faster for queries where you're just reading, not modifying.
    @Transactional(readOnly = true)
    public User getUserById(Long id) {
        // orElseThrow: if findById returns empty Optional, throw an exception.
        // This is cleaner than: if (user == null) throw ...
        return userRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("User not found with id: " + id));
    }

    @Transactional(readOnly = true)
    public User getUserByEmail(String email) {
        return userRepository.findByEmail(email)
                .orElseThrow(() -> new RuntimeException("User not found with email: " + email));
    }

    // Pageable contains: page number, page size, and sort direction.
    // Spring Data's findAll(Pageable) generates:
    //   SELECT * FROM users ORDER BY ... LIMIT ? OFFSET ?
    //
    // Page<User> wraps the results with metadata:
    //   - content: the list of users for this page
    //   - totalElements: total users across all pages
    //   - totalPages: how many pages exist
    //   - number: current page number (0-based)
    @Transactional(readOnly = true)
    public Page<User> getAllUsers(Pageable pageable) {
        return userRepository.findAll(pageable);
    }

    @Transactional(readOnly = true)
    public List<User> getUsersByStatus(UserStatus status) {
        return userRepository.findByStatus(status);
    }

    // ==================== UPDATE ====================

    @Transactional
    public User updateUser(Long id, User updatedData) {
        User existingUser = getUserById(id);

        // Only update fields that are provided (not null).
        // This prevents accidentally wiping out fields the caller didn't send.
        if (updatedData.getFirstName() != null) {
            existingUser.setFirstName(updatedData.getFirstName());
        }
        if (updatedData.getLastName() != null) {
            existingUser.setLastName(updatedData.getLastName());
        }
        if (updatedData.getPhoneNumber() != null) {
            existingUser.setPhoneNumber(updatedData.getPhoneNumber());
        }

        // No need to call save() explicitly here!
        // Because this method is @Transactional, Hibernate tracks changes to "existingUser".
        // When the transaction commits, Hibernate detects the modified fields
        // and automatically generates an UPDATE query. This is called "dirty checking".
        return existingUser;
    }

    // ==================== DELETE ====================

    @Transactional
    public void deleteUser(Long id) {
        User user = getUserById(id);
        userRepository.delete(user);
    }
}
